# # from collections import defaultdict

# tip_comments = [
    (
        id: 1,
        tip_id: 1,
        user_id: 1,
        "body": Survival is all about knowledge. Thanks for boosting mine!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 2,
        tip_id: 1,
        user_id: 2,
        "body": Thanks for sharing these survival gems. I'm taking notes!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 3,
        tip_id: 2,
        user_id: 3,
        "body": I'm intrigued... Are these survival tips from personal experience,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 4,
        tip_id: 2,
        user_id: 4,
        "body": I'm intrigued... Are these survival tips from personal experience,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 5,
        tip_id: 3,
        user_id: 5,
        "body": I'm intrigued... Are these survival tips from personal experience,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 6,
        tip_id: 4,
        user_id: 6,
        "body": In a pinch, these tips could be a lifesaver. Thanks!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 7,
        tip_id: 5,
        user_id: 7,
        "body": In a pinch, these tips could be a lifesaver. Thanks!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 8,
        tip_id: 5,
        user_id: 8,
        "body": In a pinch, these tips could be a lifesaver. Thanks!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 9,
        tip_id: 6,
        user_id: 9,
        "body": Not sure how practical these are for me, but thanks.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 10,
        tip_id: 6,
        user_id: 10,
        "body": Not sure how practical these are for me, but thanks.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 11,
        tip_id: 7,
        user_id: 11,
        "body": Not sure how practical these are for me, but thanks.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 12,
        tip_id: 8,
        user_id: 12,
        "body": Really thankful there are people like you out there making tips like this for us to follow!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 13,
        tip_id: 8,
        user_id: 13,
        "body": Really thankful there are people like you out there making tips like this for us to follow!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 14,
        tip_id: 8,
        user_id: 14,
        "body": Really thankful there are people like you out there making tips like this for us to follow!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 15,
        tip_id: 9,
        user_id: 15,
        "body": Really thankful there are people like you out there making tips like this for us to follow!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 16,
        tip_id: 10,
        user_id: 16,
        "body": Survival is all about knowledge. Thanks for boosting mine!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 17,
        tip_id: 10,
        user_id: 17,
        "body": Survival is all about knowledge. Thanks for boosting mine!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 18,
        tip_id: 10,
        user_id: 18,
        "body": Nice tip! Appreciate it!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 19,
        tip_id: 11,
        user_id: 19,
        "body": How many people wanna go out there and trip applying these tips right now?,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 20,
        tip_id: 12,
        user_id: 20,
        "body": In a pinch, these tips could be a lifesaver. Thanks!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 21,
        tip_id: 12,
        user_id: 21,
        "body": Thanks for the tips, I'll still manage to mess it up.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 22,
        tip_id: 13,
        user_id: 22,
        "body": Thanks for the tips, I'll still manage to mess it up.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 23,
        tip_id: 14,
        user_id: 23,
        "body": Survival tips that make me question what I know about emergencies.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 24,
        tip_id: 15,
        user_id: 24,
        "body": Thanks for sharing these survival gems. I'm taking notes!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 25,
        tip_id: 15,
        user_id: 25,
        "body": Thanks for sharing these survival gems. I'm taking notes!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 26,
        tip_id: 16,
        user_id: 26,
        "body": Survival tips that make me question what I know about emergencies.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 27,
        tip_id: 17,
        user_id: 27,
        "body": Survival tips that make me question what I know about emergencies.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 28,
        tip_id: 18,
        user_id: 28,
        "body": Survival is all about knowledge. Thanks for boosting mine!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 29,
        tip_id: 19,
        user_id: 29,
        "body": Survival is all about knowledge. Thanks for boosting mine!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 30,
        tip_id: 20,
        user_id: 30,
        "body": Thanks for sharing these survival gems. I'm taking notes!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 31,
        tip_id: 21,
        user_id: 31,
        "body": Thanks for sharing these survival gems. I'm taking notes!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 32,
        tip_id: 22,
        user_id: 32,
        "body": Thanks for sharing these survival gems. I'm taking notes!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 33,
        tip_id: 23,
        user_id: 33,
        "body": Survival is all about knowledge. Thanks for boosting mine!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 34,
        tip_id: 24,
        user_id: 34,
        "body": Survival tips that make me question what I know about emergencies.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 35,
        tip_id: 25,
        user_id: 35,
        "body": Thanks for the tips, I'll still manage to mess it up.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 36,
        tip_id: 26,
        user_id: 36,
        "body": Thanks for the tips, I'll still manage to mess it up.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 37,
        tip_id: 27,
        user_id: 37,
        "body": Survival is all about knowledge. Thanks for boosting mine!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 38,
        tip_id: 28,
        user_id: 38,
        "body": Survival is all about knowledge. Thanks for boosting mine!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 39,
        tip_id: 29,
        user_id: 39,
        "body": Survival is all about knowledge. Thanks for boosting mine!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 40,
        tip_id: 29,
        user_id: 40,
        "body": Survival is all about knowledge. Thanks for boosting mine!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 41,
        tip_id: 30,
        user_id: 41,
        "body": In a pinch, these tips could be a lifesaver. Thanks!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 42,
        tip_id: 30,
        user_id: 42,
        "body": Thanks for the tips, I'll still manage to mess it up.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 43,
        tip_id: 31,
        user_id: 43,
        "body": Because nothing says 'hopeless' like survival tactics.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 44,
        tip_id: 31,
        user_id: 44,
        "body": Survival tips that make me question what I know about emergencies.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 45,
        tip_id: 32,
        user_id: 45,
        "body": Survival tips that make me question what I know about emergencies.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 46,
        tip_id: 33,
        user_id: 46,
        "body": Survival tips that make me question what I know about emergencies.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 47,
        tip_id: 34,
        user_id: 47,
        "body": Because nothing says 'hopeless' like survival tactics.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 48,
        tip_id: 35,
        user_id: 48,
        "body": Because nothing says 'hopeless' like survival tactics.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 49,
        tip_id: 36,
        user_id: 49,
        "body": These survival tips serve as a reminder of the dangers out there.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 50,
        tip_id: 36,
        user_id: 50,
        "body": These survival tips serve as a reminder of the dangers out there.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 51,
        tip_id: 37,
        user_id: 2,
        "body": These survival tips serve as a reminder of the dangers out there.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 52,
        tip_id: 38,
        user_id: 2,
        "body": Because nothing says 'hopeless' like survival tactics.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 53,
        tip_id: 39,
        user_id: 4,
        "body": Sad to consider a world where these survival tips are necessary.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 54,
        tip_id: 40,
        user_id: 3,
        "body": Sad to consider a world where these survival tips are necessary.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 55,
        tip_id: 41,
        user_id: 17,
        "body": Because nothing says 'hopeless' like survival tactics.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 56,
        tip_id: 42,
        user_id: 24,
        "body": Sad to consider a world where these survival tips are necessary.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 57,
        tip_id: 42,
        user_id: 28,
        "body": Interesting advice. Hope I never have to use it.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 58,
        tip_id: 43,
        user_id: 33,
        "body": I hope I never have to use these...,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 59,
        tip_id: 43,
        user_id: 32,
        "body": You never know when it'll come in handy though!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 60,
        tip_id: 44,
        user_id: 35,
        "body": I hope I never have to use these...,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 61,
        tip_id: 45,
        user_id: 39,
        "body": Thanks for the tips, I'll still manage to mess it up.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 62,
        tip_id: 46,
        user_id: 36,
        "body": How many people wanna go out there and trip applying these tips right now?,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 63,
        tip_id: 47,
        user_id: 42,
        "body": How many people wanna go out there and trip applying these tips right now?,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 64,
        tip_id: 48,
        user_id: 44,
        "body": How many people wanna go out there and trip applying these tips right now?,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 65,
        tip_id: 49,
        user_id: 48,
        "body": As if I needed more reminders of how unprepared I am.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 66,
        tip_id: 50,
        user_id: 50,
        "body": As if I needed more reminders of how unprepared I am.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 67,
        tip_id: 50,
        user_id: 12,
        "body": As if I needed more reminders of how unprepared I am.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 68,
        tip_id: 51,
        user_id: 14,
        "body": As if I needed more reminders of how unprepared I am.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 69,
        tip_id: 52,
        user_id: 16,
        "body": As if I needed more reminders of how unprepared I am.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 70,
        tip_id: 53,
        user_id: 19,
        "body": As if I needed more reminders of how unprepared I am.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 71,
        tip_id: 54,
        user_id: 22,
        "body": How many people wanna go out there and trip applying these tips right now?,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 72,
        tip_id: 55,
        user_id: 24,
        "body": How many people wanna go out there and trip applying these tips right now?,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 73,
        tip_id: 55,
        user_id: 4,
        "body": How many people wanna go out there and trip applying these tips right now?,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 74,
        tip_id: 56,
        user_id: 2,
        "body": How many people wanna go out there and trip applying these tips right now?,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 75,
        tip_id: 57,
        user_id: 18,
        "body": Nice tip! Appreciate it!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 76,
        tip_id: 57,
        user_id: 20,
        "body": Nice tip! Appreciate it!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 77,
        tip_id: 57,
        user_id: 25,
        "body": Nice tip! Appreciate it!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 78,
        tip_id: 58,
        user_id: 26,
        "body": Nice tip! Appreciate it!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 79,
        tip_id: 59,
        user_id: 26,
        "body": Survival for dummies, perfect.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 80,
        tip_id: 60,
        user_id: 14,
        "body": Survival for dummies, perfect.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 81,
        tip_id: 60,
        user_id: 10,
        "body": Survival for dummies, perfect.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 82,
        tip_id: 61,
        user_id: 3,
        "body": Survival for dummies, perfect.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 83,
        tip_id: 62,
        user_id: 10,
        "body": In a pinch, these tips could be a lifesaver. Thanks!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 84,
        tip_id: 63,
        user_id: 44,
        "body": In a pinch, these tips could be a lifesaver. Thanks!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 85,
        tip_id: 64,
        user_id: 48,
        "body": In a pinch, these tips could be a lifesaver. Thanks!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 86,
        tip_id: 65,
        user_id: 50,
        "body": These survival tips are something I'll file away for later.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 87,
        tip_id: 66,
        user_id: 23,
        "body": Survival for dummies, perfect.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 88,
        tip_id: 47,
        user_id: 24,
        "body": Survival expert in the making these tips prove it!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 89,
        tip_id: 52,
        user_id: 29,
        "body": These survival tips are something I'll file away for later.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 90,
        tip_id: 55,
        user_id: 35,
        "body": These survival tips are something I'll file away for later.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 91,
        tip_id: 58,
        user_id: 37,
        "body": These survival tips are something I'll file away for later.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 92,
        tip_id: 49,
        user_id: 34,
        "body": Survival expert in the making these tips prove it!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 93,
        tip_id: 32,
        user_id: 32,
        "body": Survival expert in the making these tips prove it!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 94,
        tip_id: 53,
        user_id: 15,
        "body": Survival expert in the making these tips prove it!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 95,
        tip_id: 65,
        user_id: 18,
        "body": Survival expert in the making these tips prove it!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 96,
        tip_id: 66,
        user_id: 23,
        "body": Nice tip! Appreciate it!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 97,
        tip_id: 42,
        user_id: 35,
        "body": Nice tip! Appreciate it!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 98,
        tip_id: 13,
        user_id: 28,
        "body": Nice tip! Appreciate it!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 99,
        tip_id: 10,
        user_id: 38,
        "body": Nice tip! Appreciate it!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 100,
        tip_id: 9,
        user_id: 21,
        "body": These survival tips are something I'll file away for later.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 101,
        tip_id: 34,
        user_id: 22,
        "body": These survival tips are something I'll file away for later.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 102,
        tip_id: 34,
        user_id: 34,
        "body": These survival tips are something I'll file away for later.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 103,
        tip_id: 38,
        user_id: 41,
        "body": These survival tips are something I'll file away for later.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 104,
        tip_id: 38,
        user_id: 32,
        "body": You're on fire! These tips showcase your survival prowess.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 105,
        tip_id: 38,
        user_id: 35,
        "body": You're on fire! These tips showcase your survival prowess.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 106,
        tip_id: 18,
        user_id: 18,
        "body": You're on fire! These tips showcase your survival prowess.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 107,
        tip_id: 24,
        user_id: 13,
        "body": You're on fire! These tips showcase your survival prowess.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 108,
        tip_id: 22,
        user_id: 10,
        "body": You're on fire! These tips showcase your survival prowess.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 109,
        tip_id: 23,
        user_id: 5,
        "body": Nice tip! Appreciate it!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 110,
        tip_id: 23,
        user_id: 4,
        "body": Thanks for the tip!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 111,
        tip_id: 27,
        user_id: 4,
        "body": Thanks for the tip!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 112,
        tip_id: 9,
        user_id: 2,
        "body": I'm intrigued... Are these survival tips from personal experience,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 113,
        tip_id: 34,
        user_id: 18,
        "body": Thanks for the tip!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 114,
        tip_id: 34,
        user_id: 18,
        "body": Thanks for the tip!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 115,
        tip_id: 38,
        user_id: 17,
        "body": Nailed it! These are the tricks of the survival trade!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 116,
        tip_id: 38,
        user_id: 36,
        "body": Nailed it! These are the tricks of the survival trade!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 117,
        tip_id: 38,
        user_id: 38,
        "body": Nailed it! These are the tricks of the survival trade!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 118,
        tip_id: 18,
        user_id: 41,
        "body": Not sure how practical these are for me, but thanks.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 119,
        tip_id: 24,
        user_id: 42,
        "body": Survival tips to clutter my brain. Great.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 120,
        tip_id: 22,
        user_id: 32,
        "body": Survival tips to clutter my brain. Great.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 121,
        tip_id: 26,
        user_id: 37,
        "body": Survival tips to clutter my brain. Great.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 122,
        tip_id: 22,
        user_id: 32,
        "body": Nailed it! These are the tricks of the survival trade!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 123,
        tip_id: 24,
        user_id: 30,
        "body": Thanks for the tip!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 124,
        tip_id: 23,
        user_id: 17,
        "body": Thanks for the tip!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 125,
        tip_id: 21,
        user_id: 32,
        "body": Interesting advice. Hope I never have to use it.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 125,
        tip_id: 21,
        user_id: 38,
        "body": Interesting advice. Hope I never have to use it.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 126,
        tip_id: 23,
        user_id: 28,
        "body": Interesting advice. Hope I never have to use it.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 127,
        tip_id: 29,
        user_id: 34,
        "body": Thanks for the tip!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 128,
        tip_id: 22,
        user_id: 12,
        "body": Thanks for the tip!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 129,
        tip_id: 34,
        user_id: 45,
        "body": Nice tip! Appreciate it!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 130,
        tip_id: 27,
        user_id: 32,
        "body": Nice tip! Appreciate it!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 131,
        tip_id: 23,
        user_id: 7,
        "body": Nice tip! Appreciate it!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 132,
        tip_id: 22,
        user_id: 7,
        "body": Nice tip! Appreciate it!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 133,
        tip_id: 26,
        user_id: 3,
        "body": Nice tip! Appreciate it!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 134,
        tip_id: 22,
        user_id: 15,
        "body": Not sure how practical these are for me, but thanks.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 135,
        tip_id: 24,
        user_id: 20,
        "body": Not sure how practical these are for me, but thanks.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 136,
        tip_id: 23,
        user_id: 32,
        "body": Not sure how practical these are for me, but thanks.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 137,
        tip_id: 21,
        user_id: 14,
        "body": Not sure how practical these are for me, but thanks.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 138,
        tip_id: 21,
        user_id: 15,
        "body": Survival tips to clutter my brain. Great.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 139,
        tip_id: 66,
        user_id: 13,
        "body": Nice tip! Appreciate it!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 140,
        tip_id: 64,
        user_id: 10,
        "body": Nice tip! Appreciate it!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 141,
        tip_id: 64,
        user_id: 32,
        "body": Nice tip! Appreciate it!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 142,
        tip_id: 63,
        user_id: 42,
        "body": Nice tip! Appreciate it!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 143,
        tip_id: 66,
        user_id: 42,
        "body": Nice tip! Appreciate it!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 144,
        tip_id: 23,
        user_id: 1,
        "body": Nice tip! Appreciate it!,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 145,
        tip_id: 61,
        user_id: 12,
        "body": Nice tip! Appreciate it!,
        "date_created" = datetime(2023, 8, 8),
    ),
        (
        id: 146,
        tip_id: 61,
        user_id: 32,
        "body": Interesting advice. Hope I never have to use it.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 147,
        tip_id: 63,
        user_id: 42,
        "body": Interesting advice. Hope I never have to use it.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 148,
        tip_id: 66,
        user_id: 42,
        "body": Interesting advice. Hope I never have to use it.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 149,
        tip_id: 20,
        user_id: 1,
        "body": Interesting advice. Hope I never have to use it.,
        "date_created" = datetime(2023, 8, 8),
    ),
    (
        id: 150,
        tip_id: 20,
        user_id: 12,
        "body": Really thankful there are people like you out there making tips like this for us to follow!,
        "date_created" = datetime(2023, 8, 8),
    ),
# ]

# # comment_counts = defaultdict(int)

# # # Count the comments for each tip_id
# # for comment in tip_comments:
# #     tip_id = comment['tip_id']
# #     comment_counts[tip_id] += 1

# # # Print the comment counts for each tip_id
# # for tip_id, count in comment_counts.items():
# #     print(fTip ID (tip_id) has (count) comments.)